version: "3"
services:
  rules_engine:
    read_only: true
    deploy:
      replicas: 1
      restart_policy:
        condition: any
      resources:
        limits:
          cpus: '0.20'
          memory: 64M
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        monitor: 60s
        max_failure_ratio: 0.3
    image: chrisns/mqtt_logger:${DRONE_BUILD_NUMBER}
    environment:
      - USER=${USER}
      - PASS=${PASS}
      - MQTT=${MQTT}